"""
pr_generator.py — Branch + PR creation with HITL checklist.

Creates git branches, applies template diffs, generates PR bodies
with automated checklists, and tracks in pr_queue.
"""
from __future__ import annotations

import logging
import subprocess
import re
from datetime import datetime, timezone
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

log = logging.getLogger("seo_agent.pr_generator")


# ── PR Template ──────────────────────────────────────────────────────────────

PR_BODY_TEMPLATE = """## SEO(playbook): Owner page — {head_term} — {site_domain}

### Description
{description}

### Changes
{changes_summary}

### Automated Checklist
- [ ] Title & H1 owner exact-match for head-term
- [ ] JSON-LD: LocalBusiness + OfferCatalog + FAQPage present
- [ ] JSON-LD validates (no errors in Rich Results Test)
- [ ] Canonical → self, trailing slash consistent
- [ ] Internal links: homepage → owner + {link_count} traffic pages → owner
- [ ] Sitemap updated with owner URL
- [ ] Meta description CTR-optimized (price, rating, CTA)
- [ ] Tests passed (lint, schema validate)
- [ ] Freeze check passed (site.freeze_until = {freeze_status})

### Rules Engine Result
```json
{rules_result}
```

### Files Modified
{files_list}

### Review Instructions
1. Verify JSON-LD with [Rich Results Test](https://search.google.com/test/rich-results)
2. Check live preview rendering
3. Approve or request changes

---
*Generated by SEO Agent v0.1.0 — {timestamp}*
"""


@dataclass
class PRRequest:
    """Request to create a PR."""
    site_domain: str
    head_term: str
    slug: str
    description: str = ""
    changes_summary: str = ""
    files_changed: list[str] = field(default_factory=list)
    link_count: int = 0
    freeze_status: str = "not frozen"
    rules_result: str = "{}"


@dataclass
class PRResult:
    """Result of PR creation."""
    success: bool
    branch_name: str = ""
    pr_url: str = ""
    pr_body: str = ""
    error: str = ""


def generate_branch_name(site_domain: str, slug: str) -> str:
    """Generate branch name: agent/seo/<site>-owner-<slug>-<timestamp>."""
    site_clean = re.sub(r"[^a-z0-9]", "", site_domain.split(".")[0])
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M")
    return f"agent/seo/{site_clean}-owner-{slug}-{ts}"


def generate_pr_body(request: PRRequest) -> str:
    """Generate PR body from template."""
    files_list = "\n".join(f"- `{f}`" for f in request.files_changed) or "_(no files listed)_"

    return PR_BODY_TEMPLATE.format(
        head_term=request.head_term,
        site_domain=request.site_domain,
        description=request.description or f"Owner page setup for '{request.head_term}' on {request.site_domain}",
        changes_summary=request.changes_summary or "JSON-LD + meta description + internal links",
        link_count=request.link_count,
        freeze_status=request.freeze_status,
        rules_result=request.rules_result,
        files_list=files_list,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


def create_branch(branch_name: str, repo_dir: str) -> tuple[bool, str]:
    """Create and checkout a new git branch."""
    try:
        result = subprocess.run(
            ["git", "checkout", "-b", branch_name],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return False, f"git checkout -b failed: {result.stderr.strip()}"
        return True, f"Branch {branch_name} created"
    except Exception as e:
        return False, str(e)


def stage_and_commit(
    files: list[str],
    message: str,
    repo_dir: str,
) -> tuple[bool, str]:
    """Stage files and commit."""
    try:
        # Stage
        result = subprocess.run(
            ["git", "add"] + files,
            cwd=repo_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return False, f"git add failed: {result.stderr.strip()}"

        # Commit
        result = subprocess.run(
            ["git", "commit", "-m", message],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return False, f"git commit failed: {result.stderr.strip()}"

        return True, result.stdout.strip()
    except Exception as e:
        return False, str(e)


def push_branch(branch_name: str, repo_dir: str) -> tuple[bool, str]:
    """Push branch to origin."""
    try:
        result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            stderr = result.stderr.strip()
            # "Everything up-to-date" is not an error
            if "up-to-date" in stderr.lower():
                return True, "Already pushed"
            return False, f"git push failed: {stderr}"
        return True, "Pushed successfully"
    except Exception as e:
        return False, str(e)


def generate_pr(
    request: PRRequest,
    repo_dir: str,
    files_to_stage: Optional[list[str]] = None,
    dry_run: bool = False,
) -> PRResult:
    """
    Full PR generation flow:
      1. Create branch
      2. Stage + commit changes
      3. Push branch
      4. Return PR body (GitHub PR creation is manual/HITL)
    
    In dry_run mode, only generates branch name + PR body without git ops.
    """
    branch_name = generate_branch_name(request.site_domain, request.slug)
    pr_body = generate_pr_body(request)

    if dry_run:
        return PRResult(
            success=True,
            branch_name=branch_name,
            pr_body=pr_body,
        )

    # 1. Create branch
    ok, msg = create_branch(branch_name, repo_dir)
    if not ok:
        return PRResult(success=False, branch_name=branch_name, error=msg)

    # 2. Stage + commit
    if files_to_stage:
        commit_msg = (
            f"seo(playbook): owner page {request.head_term} — {request.site_domain}\n\n"
            f"{request.changes_summary}"
        )
        ok, msg = stage_and_commit(files_to_stage, commit_msg, repo_dir)
        if not ok:
            return PRResult(success=False, branch_name=branch_name, error=msg)

    # 3. Push
    ok, msg = push_branch(branch_name, repo_dir)
    if not ok:
        return PRResult(success=False, branch_name=branch_name, error=msg)

    log.info(f"PR ready: branch={branch_name}")
    return PRResult(
        success=True,
        branch_name=branch_name,
        pr_body=pr_body,
    )
