"""
validate_jsonld.py — JSON-LD schema validator for CI.

Validates JSON-LD generated by template_engine against schema.org rules.
Exit non-zero on errors to block PR merge.

Usage:
  python -m agent.seo_agent.validate_jsonld
  python -m agent.seo_agent.validate_jsonld --file path/to/schema.json
"""
from __future__ import annotations

import json
import sys
import logging
from typing import Optional

log = logging.getLogger("seo_agent.validate_jsonld")

# ── Schema.org Type Requirements ──────────────────────────────────────────────

REQUIRED_FIELDS = {
    "LocalBusiness": ["name", "url", "telephone", "@context"],
    "FAQPage": ["mainEntity", "@context"],
    "BreadcrumbList": ["itemListElement", "@context"],
    "OfferCatalog": ["itemListElement"],
    "Offer": ["name", "price", "priceCurrency"],
    "AggregateRating": ["ratingValue", "reviewCount"],
    "Question": ["name", "acceptedAnswer"],
    "Answer": ["text"],
    "ListItem": ["position", "name"],
}

VALID_TYPES = set(REQUIRED_FIELDS.keys()) | {
    "City", "AdministrativeArea", "ItemList",
}


def validate_schema(schema: dict, path: str = "") -> list[str]:
    """Validate a single JSON-LD schema object. Returns list of errors."""
    errors = []
    schema_type = schema.get("@type", "")

    if not schema_type:
        errors.append(f"{path}: missing @type")
        return errors

    # Check required fields
    required = REQUIRED_FIELDS.get(schema_type, [])
    for field in required:
        if field not in schema:
            errors.append(f"{path}{schema_type}: missing required '{field}'")

    # Type-specific validations
    if schema_type == "LocalBusiness":
        # URL must be https
        url = schema.get("url", "")
        if url and not url.startswith("https://"):
            errors.append(f"{path}LocalBusiness.url must use https (got: {url[:50]})")

        # Phone format
        phone = schema.get("telephone", "")
        if phone and not phone.startswith("+"):
            errors.append(f"{path}LocalBusiness.telephone should use E.164 format (+XX...)")

        # AggregateRating validation
        rating = schema.get("aggregateRating")
        if rating:
            errors.extend(validate_schema(rating, f"{path}LocalBusiness."))

        # OfferCatalog validation
        catalog = schema.get("hasOfferCatalog")
        if catalog:
            errors.extend(validate_schema(catalog, f"{path}LocalBusiness."))

        # areaServed should be array
        area = schema.get("areaServed")
        if area and not isinstance(area, list):
            errors.append(f"{path}LocalBusiness.areaServed should be an array")

    elif schema_type == "FAQPage":
        entities = schema.get("mainEntity", [])
        if not isinstance(entities, list):
            errors.append(f"{path}FAQPage.mainEntity must be an array")
        else:
            for i, q in enumerate(entities):
                errors.extend(validate_schema(q, f"{path}FAQ[{i}]."))
                answer = q.get("acceptedAnswer")
                if answer:
                    errors.extend(validate_schema(answer, f"{path}FAQ[{i}].answer."))

    elif schema_type == "BreadcrumbList":
        items = schema.get("itemListElement", [])
        if not isinstance(items, list):
            errors.append(f"{path}BreadcrumbList.itemListElement must be an array")
        else:
            for i, item in enumerate(items):
                errors.extend(validate_schema(item, f"{path}Breadcrumb[{i}]."))

    elif schema_type == "OfferCatalog":
        items = schema.get("itemListElement", [])
        for i, offer in enumerate(items):
            errors.extend(validate_schema(offer, f"{path}Offer[{i}]."))

    elif schema_type == "Offer":
        price = schema.get("price", "")
        if price:
            try:
                float(price)
            except (ValueError, TypeError):
                errors.append(f"{path}Offer.price must be numeric (got: {price})")

    return errors


def validate_jsonld_string(jsonld_str: str) -> tuple[bool, list[str]]:
    """Validate a JSON-LD string (array or object). Returns (valid, errors)."""
    errors = []

    try:
        data = json.loads(jsonld_str)
    except json.JSONDecodeError as e:
        return False, [f"Invalid JSON: {e}"]

    if isinstance(data, list):
        schemas = data
    elif isinstance(data, dict):
        schemas = [data]
    else:
        return False, ["JSON-LD must be an object or array"]

    if not schemas:
        return False, ["JSON-LD is empty"]

    for i, schema in enumerate(schemas):
        errors.extend(validate_schema(schema, f"[{i}]."))

    return len(errors) == 0, errors


def validate_all_templates() -> tuple[bool, list[str]]:
    """
    Validate JSON-LD generated by template_engine for all test scenarios.
    Used as CI smoke test.
    """
    from .template_engine import (
        OwnerPageData, PackageOffer, FAQItem,
        generate_combined_jsonld,
    )

    all_errors = []
    scenarios = [
        # Full data
        OwnerPageData(
            brand="SuperParty", domain="superparty.ro",
            path="/animatori-petreceri-copii", phone="+40722744377",
            head_term="animatori petreceri copii",
            h1="Animatori Petreceri Copii",
            packages=[
                PackageOffer("Super 1", "490", "RON"),
                PackageOffer("Super 3", "840", "RON"),
            ],
            faqs=[
                FAQItem("Ce acoperire?", "București și Ilfov."),
            ],
        ),
        # Minimal data (no packages, no FAQs)
        OwnerPageData(
            brand="WowParty", domain="wowparty.ro",
            path="/animatori", phone="+40700000000",
            head_term="animatori", h1="Animatori",
        ),
        # Different brand
        OwnerPageData(
            brand="Animatopia", domain="animatopia.ro",
            path="/mascote", phone="+40711111111",
            head_term="mascote si personaje",
            h1="Mascote și Personaje",
            packages=[PackageOffer("Basic", "300", "RON")],
            faqs=[
                FAQItem("Q1?", "A1."),
                FAQItem("Q2?", "A2."),
            ],
        ),
    ]

    for i, data in enumerate(scenarios):
        jsonld = generate_combined_jsonld(data)
        valid, errors = validate_jsonld_string(jsonld)
        if not valid:
            all_errors.append(f"Scenario {i+1} ({data.brand}): {errors}")

    return len(all_errors) == 0, all_errors


def main():
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if len(sys.argv) > 1 and sys.argv[1] == "--file":
        # Validate a specific file
        filepath = sys.argv[2] if len(sys.argv) > 2 else ""
        if not filepath:
            print("Usage: python -m agent.seo_agent.validate_jsonld --file <path>")
            sys.exit(2)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        valid, errors = validate_jsonld_string(content)
    else:
        # Validate all template scenarios
        print("Validating all template engine scenarios...")
        valid, errors = validate_all_templates()

    if valid:
        print("✅ JSON-LD VALIDATION PASSED — all schemas valid")
        sys.exit(0)
    else:
        print("❌ JSON-LD VALIDATION FAILED:")
        for e in errors:
            print(f"  • {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
